### PR TITLE
Updated a bunch of styles and formatting

### PR DESCRIPTION
**Pull request by t8or**
Started overhauling the CSS and using flexbox inside the HTML. Still WIP, but getting there.

### CODE REVIEW

**Comment by extreme4all** [comment]
the images should be on the same line
afbeelding

**Comment by extreme4all** [comment]
i'm not sure if the blue ish color of the navigation fits, maybe a more gray is better? #2F2F2F
afbeelding

**Comment by extreme4all** [comment]
i don't think that is our logo.
the font of github, patreon, discord feels sharp
afbeelding

**Comment by hammerofthor8** [comment]
> i don't think that is our logo.
> the font of github, patreon, discord feels sharp
> afbeelding

This looks like you dont have the Roboto font installed on your computer.

**Comment by hammerofthor8** [comment]
> the images should be on the same line
> afbeelding

great call out. i haven't work on the other pages yet, so we can probably hold off on the PR until I get there.

**Comment by hammerofthor8** [comment]
and the logo is the one with the crosshair over the default skin guy, right?

**Comment by extreme4all** [comment]
i like what you did with the background

**Comment by extreme4all** [comment]
> and the logo is the one with the crosshair over the default skin guy, right?

correct

**Comment by extreme4all** [comment]
> 



> Roboto
if its not a default font we should put it on the website or load is async from a font provider

**Pull request closed without merging**
