### PR TITLE
chore: fix build and discord link

### PR DESCRIPTION
**Pull request by joeydotdev**
This PR:
* removes `package-lock.json` since we are using yarn
* fixes Discord hyperlinks (was stale before)
* fixes build on node 16 by upgrading node-sass to v6 ([ref](https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove))
* sets up prettier to auto format code on save

### CODE REVIEW

**Comment by Ferrariic** [comment]
Great work! I'll take a deep look and review in a bit and let you know if there's any changes.

**Review by ThorntonMatthewD — APPROVED** [review]

**Comment by Ferrariic** [comment]
For some reason it has trouble building, I'll take a look at this

**Comment by ThorntonMatthewD** [comment]
This is due to Node.js being on `v10.19.0` on our build server. If we upgrade it then it will work.

I tested this PR on my PC which runs `v17.3.0`.

**Comment by Ferrariic** [comment]
Sweet tyvm!

**Pull request merged**
